[project]
name = "hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "jotsu-mcp>=0.3.0",
]

[dependency-groups]
dev = [
    "pipdeptree>=2.26.1",
]
